services:
  #db_userservice:
  db_userservice:
    image: mysql:latest
    container_name: project2_db_userservice
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=project2_db_userservice # this line is used to create the database
    ports:
      - "3307:3306"                        
    volumes:
      - ./volumes/db_userservice:/var/lib/mysql                  
    networks:
      - project2
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s     # Check health every 10 seconds
      timeout: 5s       # Wait 5 seconds for a response
      retries: 3        # Retry 3 times before declaring failure  

  #kafka
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  

  db_friendservice:
    image: neo4j:latest
    container_name: project2_db_friendservice
    environment:
      - NEO4J_AUTH=neo4j/neo4j1234 #username/password
    ports:
      - "7474:7474"   
      - "7687:7687"                     
    volumes:
      - ./volumes/db_friendservice:/data                 
    networks:
      - project2
    restart: always
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j1234", "MATCH () RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 3  

  db_postservice:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: project2_db_postservice
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=username
      - MONGODB_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db_postservice:/data/db
    networks:
      - project2
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "mongodb://username:12345@localhost:27017", "--eval", "show dbs;" ]
      interval: 10s
      timeout: 5s
      retries: 3


  db_fanpagegroupservice:
    image: mysql:latest
    container_name: project2_db_fanpagegroupservice
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=project2_db_fanpagegroupservice # this line is used to create the database
    ports:
      - "3308:3306"                        
    volumes:
      - ./volumes/db_fanpagegroupservice:/var/lib/mysql                  
    networks:
      - project2
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s     # Check health every 10 seconds
      timeout: 5s       # Wait 5 seconds for a response
      retries: 3        # Retry 3 times before declaring failure  

networks:
  project2:  
    driver: bridge

