


# server
server:
  port: 8888

# app
app:
  api-prefix: /api/v1

# service
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: user_service
          uri: http://localhost:8081
          predicates:
          - Path=${app.api-prefix}/user/**
          filters:
          - StripPrefix=2

  #Redis
  redis:
    host: localhost
    port: 6379
