spring:
  application:
    name: NotifiService
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
app:
  services:
    user: http://localhost:8080/user
    group: http://localhost:8084/group
    friend: http://localhost:8082/friend
    fanpage: http://localhost:8084/fanpage
